import { faker } from '@faker-js/faker';

export const ListCard = [
  { description: 'Estou bem', img: faker.image.avatarGitHub() },
  { description: 'Alteração na urina', img: faker.image.avatarGitHub() },
  { description: 'Alteração na visão', img: faker.image.avatarGitHub() },
  { description: 'Alteração na voz', img: faker.image.avatarGitHub() },
  { description: 'Cansaço', img: faker.image.urlPlaceholder() },
  { description: 'Chiado no peito', img: faker.image.avatarGitHub() },
  { description: 'Diarréia', img: faker.image.avatarGitHub() },
  { description: 'Dificuldade', img: faker.image.avatarGitHub() },
  { description: 'Dor (todas)', img: faker.image.avatarGitHub() },
  { description: 'Dor nas articulações', img: faker.image.avatarGitHub() },
  { description: 'Dormência', img: faker.image.avatarGitHub() },
  { description: 'Enjoo', img: faker.image.avatarGitHub() },
  { description: 'Falta de apetite', img: faker.image.avatarGitHub() },
  { description: 'Falta de ar', img: faker.image.avatarGitHub() },
  { description: 'Febre', img: faker.image.avatarGitHub() },
  { description: 'Insônia', img: faker.image.avatarGitHub() },
  { description: 'Lesão na pele', img: faker.image.avatarGitHub() },
  { description: 'Mucosite', img: faker.image.avatarGitHub() },
  { description: 'Prisão de ventre', img: faker.image.avatarGitHub() },
  { description: 'Tontura', img: faker.image.avatarGitHub() },
  { description: 'Tosse', img: faker.image.avatarGitHub() },
  { description: 'Vômito', img: faker.image.avatarGitHub() },
];
